vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode

tasks:
  - name: Install Commitizen
    before: npm i -g commitizen

  - name: Install dependencies
    init: npm i
    openMode: tab-after
